### ISSUE TITLE
Generate LUT only uses 100 values

### ISSUE THREAD

**Issue by ezanchi** [Luke460/wheel-check-data-aggregator#1]
So I did the Linear Test with 256 values and then used this tool to generate the LUT with the recommended Aggregation Order, but the resulting LUT only had 100 values.

I then used the corrected CSV file generated by this tool and the LUT Generator program and the LUT used the original 256 values but corrected with this tool.

**Comment by Luke460** [comment]
This might be counterintuitive, but the output resolution is not related to the input resolution in a transpose function (as in lut generation). 
More importantly, I don't know if there is a limit in the game. But I can add an extra option to select the output resolution!
Thanks a lot for your questions and suggestions!

**Comment by ezanchi** [comment]
I thought that if you give the game more "tables" to look the values up, it would not need to interpolate the values that do not exist in the LUT file (averaging, maybe wrongly, the LUT).

I would just use the same number of outputs as there are inputs (thus not losing resolution nor interpolating new values)

Anyway I really have no idea how that works! 😄 

Thank you for developing this so needed tool!

**Comment by ezanchi** [comment]
A good example I just came up with is like trying to approximate a sine wave with square waves. The smaller each square, and the more of them, the better the approximation

**Comment by Luke460** [comment]
Internally, my tool always works with 1000 values during the lut generation. I could generate a huge lut, but I don't know if this can generate an input lag.

**Comment by ezanchi** [comment]
> Internally, my tool always works with 1000 values during the lut generation. I could generate a huge lut, but I don't know if this can generate an input lag.

Intuition tells me that using more output values (or internal values) as there are real CSV values would generate noise/fake values that may not reflect the real response of the wheel that particular force.

**Comment by Luke460** [comment]
Yes, but in this particular case, is like having more decimal values during a calculation. You are reversing a linearized curve, and to perfectly describe a curve you need infinite values. No fake values or noise are added thanks to the linearization.
But you can use the improved csv file in LUT Generator as well!

**Comment by ezanchi** [comment]
> Yes, but in this particular case, is like having more decimal values during a calculation. You are reversing a linearized curve, and to perfectly describe a curve you need infinite values. No fake values or noise are added thanks to the linearization.
> But you can use the improved csv file in LUT Generator as well!

I used the LUT Generator with the corrected CSV file that your tool outputs and it used 257 values (as it starts counting from 1) and so far haven't noticed anything strange in ACC.

In fact I feel the wheel is even more precise with the forces it can deliver even when it's motor is so limited in max Nm.

So if I had to guess I would say that more values in the LUT file helps the simulator to have better resolution of what the real wheel can do, and this providing a more realistic feel to the steering.

But once again, I have no idea! 😆

**Comment by Luke460** [comment]
After various calculations, I will bring the output resolution to 200 values ​​(fixed due to implementation reasons). I also fixed the chart bug. Thanks for the support as always!

**Comment by ezanchi** [comment]
I see that now the LUT generated by your tool always generates 1000 values.

Would you please explain to me why, if the input only has 256 values, the output can have 1000 values?

From my ignorant point of view, it seems that the LUT generated by your tool is somehow making up new values that weren't there on the first place.

**Comment by Luke460** [comment]
It seems that the LUT generated by your tool is somehow making up new values that weren't there on the first place.
 - - - - - 
Yes, by analyzing a dataset you can extract a curve. By interpolation you can get intermediate values and increase the resolution.
The best example that you can get is here:
[photozoompro](https://www.benvista.com/photozoompro)

There are many examples of this approach.

**Comment by ezanchi** [comment]
> It seems that the LUT generated by your tool is somehow making up new values that weren't there on the first place.
> 
> Yes, by analyzing a dataset you can extract a curve. By interpolation you can get intermediate values and increase the resolution.
> The best example that you can get is here:
> [photozoompro](https://www.benvista.com/photozoompro)
> 
> There are many examples of this approach.

I see. But by using that approach you are taking the risk of making up values that misrepresent real life wheel's behavior.

I still think the best you can do is add another slider where you can select the resolution: at the lowest, the native resolution of the CSV, and the max, the maximum number of LUT entries your tool can have, which is 1000. And maybe 8 values in-between to let the user select.

Or maybe a multiplyer of the native CSV resolution: from 1 to 5 or something like that, capped at 1000.

Just throwing some ideas 😁

**Comment by Luke460** [comment]
A second slider is not a bad idea! But I would like to explain to you how the lut file is generated, and why the output resolution is not related to the input.
So, starting from csv file 'example.csv' with 100 values:
You can see by opening it, that 12 or 13 input force values have movement 0 as response. That means that in the lut file, to have a movement zero you could send this collection of values [0,1,2,3...,11,12,13]. You can notice this by whatching at the green graph that is less smoother than the blue one near the origin because you are wasting values (In the preview you have the same output resolution). To virtually use all the values (and just one zero) you need a non-linear step in the lut file. And... It's really hard to explain (maybe I am not good enough) and I know that is very counterintuitive. I had exactly the same idea before to study those function! But no noice or fake values are added! Just put the lut file values in Excell and print a graph, you'll see what I mean ;-) Martedì, 01 Settembre 2020, 01:43AM +02:00 da ezanchi  notifications@github.com :

**Comment by ezanchi** [comment]
> A second slider is not a bad idea! But I would like to explain to you how the lut file is generated, and why the output resolution is not related to the input. So, starting from csv file 'example.csv' with 100 values: You can see by opening it, that 12 or 13 input force values have movement 0 as response. That means that in the lut file, to have a movement zero you could send this collection of values [0,1,2,3...,11,12,13]. You can notice this by watching at the green graph that is less smoother than the blue one near the origin because you are wasting values (In the preview you have the same output resolution). To virtually use all the values (and just one zero) you need a non-linear step in the lut file. Think about this: the resolution can be one to one only if the blue line has a 45° slope. If it's less, than you need more values. If it's more, you have redundant values. And... It's really hard to explain (maybe I am not good enough) and I know that is very counterintuitive. I had exactly the same idea before to study this function! But no noise or fake values are added! Just put the lut file values in Excell and print a graph, you'll see what I mean ;-)

From my understanding interpolating is making up new values that were not there from the first place, and that may be accurate or may be not.

An example would be like the ISO in the cameras. If you want to see in better in darkness you need better resolution (more data points) and more exposure (smaller increments from each data point to the next one). You can turn up the ISO a bit (interpolate), but if you turn it up too much it starts to add values to the image that were not there and that creates static noise (fake data points). Those fake data points maybe correlate to the real world, or maybe not.

I believe the approach LUT Generator is taking is just using the same number of outputs as there are inputs,, and thus not increasing the resolution but neither adding noise (interpolated values). So if you only give it 10 data points in the CSV, the resulting LUT will be very poor and only accurate to those 10 data points, and very inaccurate elsewhere. If you give it 100 or 250 points then the LUT will approach more and more to the real world wheel's behavior curve (which is continuous and not discrete).

**Comment by Luke460** [comment]
just using the same number of outputs as there are inputs
 - - -
Mathematically, you cant. 
Just try to implement (even on excell) a reverse function. It's the only way to really understand where the problem is. 
However, I really like your approach to wanting to understand things thoroughly

**Comment by ezanchi** [comment]
So, from your point of view, which one would be better in this scenario (having the most accurate Force Feedback within wheel's limitations)?:
- LUT Generator using CSV corrected with your tool;
- LUT generated BY your tool.

**Comment by Luke460** [comment]
My tool was designed to produce an improved csv. After that I wanted to improve the lut generation as well beacuse, according to my analysis, Lut Generator truncates many values near the center point of the wheel.
--
Inviato da Libero Mail per Android Martedì, 01 Settembre 2020, 02:58PM +02:00 da ezanchi  notifications@github.com :

**Comment by Luke460** [comment]
Up to version 2.3 with more than 100 values ​​in the input csv, Lut Generator is better. But since version 2.4 my tool is much more accurate both for the larger output, and (more important) for better handling of decimal values.

**Comment by ezanchi** [comment]
> Up to version 2.3 with more than 100 values in the input csv, Lut Generator is better. But since version 2.4.1 my tool is much more accurate both for the larger output, and (more important) for better handling of decimal values.

Oh I see! It seems that you understand exactly how the whole procedure works and designed/developed a tool to do a better job than the classic methods we have been using.

If that's the case then I can just close the issue as its really not an issue, just a lack of understanding from my side.

**Comment by ezanchi** [comment]
Here are my CSV and LUT (not corrected by your tool):
CSV:
https://drive.google.com/file/d/1W2EskRB3sQDJ0P0v8PJVrwV7sbLhgp5f/view
LUT:
https://drive.google.com/file/d/1eHVufjjkTNk4wBzcxLPRVFTDgBdafwJI/view

**Comment by Luke460** [comment]
This is the generated lut with the csv files:
[lut-test-AG-5](https://drive.google.com/file/d/1RiiN-EiZFA1i1ZuaW3-YTDPiP7mF2odY/view?usp=sharing)
As you can see there are many redundant zeros and the step is not constant. Remove the zeros at the start! (I left them to show you the raw transposition)

**Comment by ezanchi** [comment]
Perfect! So I can close the issue now and my mind will be in peace hahaha

Thank you for explaining everything to me. I have never done anything like this and I know that my reasoning is not how it works, but intuition is sometimes wrong! 😄

**Comment by Luke460** [comment]
Thanks to your questions and suggestions my application is now better than ever! Time to drive really hard now!
